export { default as List } from './list'
export { default as Create } from './create'
export { default as Update } from './edit'
export { default as Delete } from './delete'
export { default as Permissions } from './permissions'